# Where are your source files?
SRC_DIRS = source
# Where are your header files?
INC_DIRS = include ../library2/include

# Where are you static libraries? Give the path and full filename
STATIC_LIBS = 
# Where are your dynamic libraries
# Does not support linking dynamic libraries into static libraries
DYNAMIC_LIB_DIRS = ../library2/dynamic
LIB_NAMES = library2

# What do you want to name your library?
NAME = $(notdir $(CURDIR))
# Note: The actual file will be called 'lib<NAME>.(a/so)', however when you are
# linking it in a project the compiler will need just '-l<NAME>'

# Where do you want to put your build outputs?
OBJ_DIR = object
STATIC_DIR = static
DYNAMIC_DIR = dynamic

# Toolchain Variables
CC = gcc

include ../library.mk