# Where are your source files?
SRC_DIRS = source
SOURCES = main.c
# Where are your header files?
INC_DIRS = include
# Where are your external libraries?
STATIC_LIB_DIRS = 
DYNAMIC_LIB_DIRS = 
DYNAMIC_LIB_NAMES = 

# What do you want to name your executable?
NAME = $(notdir $(CURDIR))

# Where do you want to put your build outputs?
OBJ_DIR = build/object
EXEC_DIR = build

# Toolchain Variables
CC = gcc

include ../project.mk