# Where are your source files?
SRC_DIRS = 
SOURCES = main.c
# Where are your header files?
INC_DIRS = ../library3/include
# Where are your external libraries?
STATIC_LIB_DIRS = 
DYNAMIC_LIB_DIRS = ../library3/dynamic
LIB_NAMES = library3

# What do you want to name your executable?
NAME = $(notdir $(CURDIR))

# Where do you want to put your build outputs?
OBJ_DIR = object
EXEC_DIR = executable

include ../project.mk