# Where are your source files?
SRC_DIRS = source
# Where are your header files?
INC_DIRS = ../library2/include ../library
# Where are your external libraries?
LIB_DIRS = ../library2/build/static ../library/build/static
# What are your libraries named?
LIB_NAMES = library2 library

# What do you want to name your executable?
# Default: $(notdir $(CURDIR)), this makes the name the same as the root
# directory
NAME = $(notdir $(CURDIR))

# Where do you want you build outputs?
BUILD_DIR = build
# Where do you want to put your object files?
OBJ_DIR = $(BUILD_DIR)/object
# Where do you want your executable?
EXEC_DIR = $(BUILD_DIR)/executable

include ../project.mk