# Where are your source files?
SRC_DIRS = 
SOURCES = main.c
# Where are your header files?
INC_DIRS = ../library
# Where are your external libraries?
STATIC_LIB_DIRS = 
DYNAMIC_LIB_DIRS = ../library/build/dynamic
LIB_NAMES = library

# What do you want to name your executable?
NAME = $(notdir $(CURDIR))

# Where do you want to put your build outputs?
OBJ_DIR = build/object
EXEC_DIR = build/executable

# Toolchain Variables
CC = gcc

include ../project.mk